#7 ワークフローから情報を取ってくるコードを記述しました
tam-bourine/club-manager pull request #12
Opened 2020-11-18 06:12 UTC by Kazu950

ワークフローから情報を取ってくるコードを記述しました。

2020-11-18 06:16 UTC, 75asa commented
@Kazu950 @chiharakenta  draft pull request を使うといいよ〜
あとラベルもPoCならつけておくとGood
こんなラベルあるといいな〜ってやつは自由に作成できるからやってみて〜

2020-11-18 06:58 UTC, Kazu950 commented
@75asa 
なるほど！
次回からその方法でPRとラベル付けをしたいと思います！

2020-11-20 13:44 UTC, 75asa reviewed
@Kazu950 いくつかきになったことまとめです〜

2020-11-20 13:44 UTC, 75asa commented on index.js
> +    const inputs = {// ステップ実行時にアプリが受け取ることを期待するデータの内容を表現するオブジェクト
バリデーションつけましょうか

2020-11-20 13:44 UTC, 75asa commented on package.json
> +  "license": "ISC",
mit に

2020-11-20 13:44 UTC, 75asa commented on index.js
> +    const blocks = [
block はファイル分けましょう

2020-11-25 13:00 UTC, 75asa requested changes
気になりポイント

2020-11-25 13:00 UTC, 75asa commented on index.js
> +const ws = new WorkflowStep('new_data', {
一般的ではないアブリビは避けましょう

2020-11-25 13:00 UTC, 75asa commented on block.js
> +  {
module にそのまんま JSON いれるのは使いづらいのでは？
block.js ってよりかは blocks/inputModal.ts / openModal.ts / inpuMemberfield.ts のように細分化するしたが綺麗ですね

2020-11-25 13:00 UTC, 75asa commented on block.js
> +      "text": "活動内容"
このあたりの項目名などは定数にして TopLevel で管理しておくと後々変更に強いし見やすいです

2020-11-25 13:00 UTC, 75asa commented on index.js
> +    const inputs = {// ステップ実行時にアプリが受け取ることを期待するデータの内容を表現するオブジェクト
それとインラインコメントをワンラインで `{` 以降でかくのなんか抵抗あります（宗教）

2020-11-25 13:00 UTC, 75asa commented on index.js
> +    const outputs = [// ステップ実行が正常に完了した際に次のステップに提供するデータの保存
ここも↑に同じく

2020-11-25 13:00 UTC, 75asa commented on index.js
> +    console.log(inputs);
```suggestion
    console.log({ inputs });
```

↑するとオブジェクト的に Logging できるよ〜

2020-11-25 13:00 UTC, 75asa commented on index.js
> +    console.log(inputs);
console.info
console.error とかもあったり 👁️

2020-11-27 00:22 UTC, 75asa commented
それと PoC ではなく本ちゃん実装の PR はいつ頃作成しますか？

2020-11-27 06:39 UTC, Kazu950 commented
@75asa 
本ちゃんのPR出す上で質問なのですが、本ちゃんのPRは
PoCのブランチと別のブランチを用意してPRした方がいいですか？

2020-11-27 06:43 UTC, 75asa commented
できればわけたがきれいだよね
コミットログもマスターマージされたらのこるので
今回はスカッシュマージするけど

2020-11-27 07:12 UTC, Kazu950 commented
@75asa 
了解しました！
では、今回はスカッシュマージで次回からは別のブランチを作成して
そちらで本ちゃんのPRをだします！

2020-11-27 07:24 UTC, 75asa commented
@Kazu950 指摘した箇所が解消された Resolve してほしいです〜

2020-11-27 07:25 UTC, 75asa commented
@chiharakenta サポートお願い〜

2020-11-27 07:30 UTC, Kazu950 commented on block.js
> +  {
@75asa 
Discordでの質問については以下の通りです。

1. moduleにそのままJSONをいれる以外の方法がわからないです。。
2. 「block.jsについては、blocksディレクトリを作成してその中に格納する。その後追加される
　　入部申請用のblock kitが記述されたファイルに関してはblock.jsと別のファイルを作成し
　　blocksディレクトリに格納する」って流れで問題ないですか？
3. レビューとはまた別件なんですが、現状のコードをngrokを使用して動作確認したいのですが
　問題ありませんか？

2020-11-27 10:58 UTC, Kazu950 commented
@75asa 
記入漏れがありました🙇‍♂️
本ちゃん実装の PR に関しては月曜日中に出したいと思います！

2020-11-27 15:21 UTC, Kazu950 commented on index.js
> +const ws = new WorkflowStep('new_data', {
修正中です

2020-11-27 15:21 UTC, Kazu950 commented on block.js
> +  {
修正中です

2020-11-27 15:21 UTC, Kazu950 commented on block.js
> +      "text": "活動内容"
修正中です

2020-11-27 15:21 UTC, Kazu950 commented on index.js
> +    const outputs = [// ステップ実行が正常に完了した際に次のステップに提供するデータの保存
修正中です

2020-11-27 15:28 UTC, Kazu950 commented on index.js
> +    console.log(inputs);
なるほど！
次回から使ってみます！！

2020-11-30 07:00 UTC, Kazu950 reviewed
レビューよろしくお願いします！

2020-11-30 07:00 UTC, Kazu950 commented on package.json
> +    "ngrok": "^3.3.0"
@75asa 
ngrokなんですが、インストールして正常に動作するのですが
ESETのパーソナルファイアウォールに引っかかってしまって、
ローカルでの動作確認ができませんでした。

2020-11-30 07:00 UTC, Kazu950 commented on index.js
> +    const member2 = values.task_member2_input.member2;
@75asa 
バリデーションなんですけど、ワークフロービルダーでステップを登録する際に
すでに空白の状態だと保存できないようになっているのですが、バリデーションの
コードを記述した方が良いですか？

2020-11-30 07:15 UTC, 75asa requested changes
@chiharakenta @Kazu950 @tk-ozawa 
みました 👁️ 
`blocks/inputClub.js` は `src/slack/blocks/inputClub.js` とかにしたいですね〜

2020-11-30 07:15 UTC, 75asa commented on blocks/inputClub.js
> +const collaborator2 = '初期メンバー2';
```suggestion
const collaborator_1st = '初期メンバー1';
const collaborator_2nd = '初期メンバー2';
```

2020-11-30 07:15 UTC, 75asa commented on blocks/inputClub.js
> +const clubName = '部活動名';
@chiharakenta @Kazu950 変数名とかの記法とかをまとめたがいいと思います
（ESLint 入れたら解決ですねこの辺は... ref #20 ）

2020-11-30 07:15 UTC, 75asa commented on blocks/inputClub.js
> +const inputClub = [
```suggestion
const inputClubModal = [
```
などのように file name で既に inputClub.js と銘打ってるんで、モーダルなどの実際に何をする変数なのかを定義した方が export, inport した際に（module, require も一緒）わかりやすいので僕は好きです
e.g. inputClubModal, modal, form, modalInputClub .....

2020-11-30 07:15 UTC, 75asa commented on blocks/inputClub.js
>      }
inputClubjs でコンポーネントごとに分割できるともっとみやすいですね
e.g. 
```
const input_component_member_1st =   {
    "type": "input",	    "type": "input",
    "block_id": "task_member_input",	    "block_id": "task_member1_input",
    "element": {	    "element": {
      "type": "plain_text_input",	      "type": "plain_text_input",
      "action_id": "member",	      "action_id": "member1",
      "placeholder": {	      "placeholder": {
        "type": "plain_text",	        "type": "plain_text",
        "text": "Add a task name"	        "text": "Add a task name"
      }	      }
    },	    },
    "label": {	    "label": {
      "type": "plain_text",	      "type": "plain_text",
      "text": "初期メンバー"	      "text": collaborator1
    }
  }
...
```

2020-11-30 07:15 UTC, 75asa commented on index.js
> +require('dotenv').config();
```suggestion
const dotenv = require('dotenv').config();

Object.keys(dotenv).forEach(key => {
  process.env[key] = dotenv[key];
});
```

こうだったかな？すると nodemon などの dev サーバー立ててる時に env 内の内容を変えても内容を更新できます

2020-11-30 07:15 UTC, 75asa commented on index.js
> +const workflowStep = new WorkflowStep('new_data', {
data っていう名称はスコープが広すぎるので控えましょう
代わりに... -> https://dev.to/dcwither/stop-using-data-as-a-variable-name-3954

2020-11-30 07:15 UTC, 75asa commented on index.js
> +    const member2 = values.task_member2_input.member2;
```suggestion
    const member1 = values.task_member1_input.member1;
    const member2 = values.task_member2_input.member2;
```

1, 2 だけだと順番を担保できないので明示したいです
e.g. 1st, 2nd

2020-11-30 07:15 UTC, 75asa commented on index.js
> +    const inputs = {
ここは何の inputs かを書いたが丁寧な気がしました cuz on index.js, 他にも inputs を受ける可能性もある

2020-11-30 07:15 UTC, 75asa commented on index.js
> +    const outputs = [
なんの outpus かを明示的にした方が丁寧かと思いました

2020-11-30 07:15 UTC, 75asa commented on index.js
> +    await update({ inputs, outputs });
全体的にですが await で実行してる Slack API のエラー処理とかは大丈夫でしょうか？
ここだと promise の戻り値でエラーロギングなど

2020-11-30 07:15 UTC, 75asa commented on index.js
>      const outputs = {
`const outpus = ` 二回目？

2020-11-30 07:15 UTC, 75asa commented on package.json
> +    "ngrok": "^3.3.0"
ngrok は devDependencies ですかね

2020-11-30 07:16 UTC, 75asa commented
@Kazu950 それと GitHub 本名も登録しておいてほしいです（メンションが出ない）

2020-11-30 07:19 UTC, 75asa commented on index.js
> +    const member2 = values.task_member2_input.member2;
@Kazu950 あー、そうでしたね！であればコード上でのバリデはいらないです〜 👍🏾

2020-11-30 07:20 UTC, 75asa commented on package.json
> +    "ngrok": "^3.3.0"
@Kazu950 なるほど この辺りが参考になるかも 👁️ 
https://techracho.bpsinc.jp/hachi8833/2020_03_06/88256

2020-12-01 08:36 UTC, 75asa commented
それとだけど functions/ に実際のコードいれるとおもうのね
なのでこ PR は PoC としてアーカイブにしたがええきがしてる

2020-12-01 11:20 UTC, Kazu950 commented
@75asa 
レビューはこのPRで行って本ちゃんのPRに関しては
別のブランチを用意してそちらにリモートリポジトリのmasterをpull
してきて、function/ に僕の書いたコードをいれる + 必要なpackageのインストール
をするっていう認識で大丈夫ですか？？

2020-12-01 11:39 UTC, 75asa commented
> @75asa 
> レビューはこのPRで行って本ちゃんのPRに関しては
> 別のブランチを用意してそちらにリモートリポジトリのmasterをpull
> してきて、function/ に僕の書いたコードをいれる + 必要なpackageのインストール
> をするっていう認識で大丈夫ですか？？
> 
> 

@Kazu950 レビューはもうしちゃったので、別途PRをつくりましょう
そして今回かいてるコードって firebase function で走らせるコードですよね
となるとはじめから function/src でコードかいたがいいとおもってて
かつ functions で動かせるコードにしないと…って感じです

なので指摘した箇所は意識しつつ
コードのロジックとかは再利用して
master pull 後から function/ でコードかいてみてください〜

2020-12-01 11:40 UTC, 75asa commented
そうですね
firebase function ってデフォルトで functions/ になっちゃってるけど
これを src/functions/ とかにしたいですね

2020-12-01 11:53 UTC, Kazu950 commented
@75asa 
了解しました！
src/functions/ にしちゃうとsrc/sheet とかぶってしまうんですけど
どうしたらいいですか？
あと、新しいPR作成後もPoCをpushしても問題ないですか？

2020-12-01 11:57 UTC, 75asa commented
> @75asa 
> 了解しました！
> src/functions/ にしちゃうとsrc/sheet とかぶってしまうんですけど
> どうしたらいいですか？

ん？いいのでは？
イメージこんなんですね

- src/
  - functions/（slack bolt）
  - sheet/（GAS）

> あと、新しいPR作成後もPoCをpushしても問題ないですか？

@Kazu950 これどういうことでしょうか？

2020-12-01 12:02 UTC, 75asa commented
> > あと、新しいPR作成後もPoCをpushしても問題ないですか？
> 
> @Kazu950 これどういうことでしょうか？
> 

コードはチェリーピックとかしてもいいですよ〜
もしくは一旦コピペとかでもおけです

2020-12-01 12:42 UTC, Kazu950 commented
@75asa 
> ん？いいのでは？
イメージこんなんですね

- src/
  - functions/（slack bolt）
  - sheet/（GAS）
> 
あ！すみません、勘違いしてました🙇‍♂️
src/functions/ で大丈夫です！

> コードはチェリーピックとかしてもいいですよ〜
もしくは一旦コピペとかでもおけです
> 
了解しました！

2020-12-02 02:20 UTC, Kazu950 commented on blocks/inputClub.js
> +const clubName = '部活動名';
了解です！

2020-12-02 02:20 UTC, Kazu950 commented on blocks/inputClub.js
> +const collaborator2 = '初期メンバー2';
修正中です。

2020-12-02 02:20 UTC, Kazu950 commented on blocks/inputClub.js
> +const inputClub = [
なるほど！
修正します！

2020-12-02 02:20 UTC, Kazu950 commented on index.js
> +    const member2 = values.task_member2_input.member2;
修正中。

2020-12-02 02:20 UTC, Kazu950 commented on index.js
> +    const inputs = {
修正中です。

2020-12-02 02:20 UTC, Kazu950 commented on index.js
> +    const outputs = [
修正中です。

2020-12-02 02:20 UTC, Kazu950 commented on package.json
> +    "ngrok": "^3.3.0"
修正中です。

2020-12-02 03:32 UTC, Kazu950 commented on package.json
> +    "ngrok": "^3.3.0"
正常に動作するようになりました。
ありがとうございます！

2020-12-02 04:09 UTC, Kazu950 commented on blocks/inputClub.js
>      }
なるほど！
修正します。

2020-12-02 04:11 UTC, Kazu950 commented on index.js
> +    const outputs = [
@75asa 
現状、次のワークフローステップに対してデータを渡す
必要がないので削除しておきます！

2020-12-02 04:11 UTC, Kazu950 commented on index.js
> +    await update({ inputs, outputs });
修正中です。

2020-12-02 04:12 UTC, Kazu950 commented on index.js
>      const outputs = {
@75asa 
こちらも現状必要ないので削除しておきます！

2020-12-02 05:28 UTC, Kazu950 commented
@75asa 
firebase functions でBoltの動作確認ってできますか？
できるのであれば、ngrokはインストールしないでおこう
と思うのですが...

2020-12-02 06:08 UTC, 75asa commented
> @75asa
> firebase functions でBoltの動作確認ってできますか？
> できるのであれば、ngrokはインストールしないでおこう
> と思うのですが...

@Kazu950 はい、できます
- [Cloud Functions for Firebase 🔥 + Bolt ⚡️で勉強会用のSlack Botを作ってみる](https://qiita.com/ryo2132/items/1a7d5e2a1b80414700e3)
- [Slack アプリフレームワーク Bolt for JavaScript を Cloud Functions for Firebase で動かそう](https://qiita.com/seratch/items/3e44f58a7c8ab41f21f0)

## ローカルで使う場合
- [ローカル環境でCloud Functions for Firebase（特にCallable関数）の動作テストをする](https://qiita.com/zaburo/items/9698ccb26dd4e0c37ab0)

2020-12-02 06:30 UTC, Kazu950 commented
@75asa 
了解です！
参考資料までありがとうございます🙇‍♂️

2020-12-02 08:26 UTC, Kazu950 commented
@75asa 
何度も質問して申し訳ないです🙇‍♂️
firebase functions:config:setコマンドを使って環境変数を設定しようとしたのですが
firebase にログインしてくださいとでます。
この場合、自身のGoogleアカウントでログインすればいいですか？

2020-12-02 10:01 UTC, 75asa commented
> @75asa 
> 何度も質問して申し訳ないです🙇‍♂️
> firebase functions:config:setコマンドを使って環境変数を設定しようとしたのですが
> firebase にログインしてくださいとでます。
> この場合、自身のGoogleアカウントでログインすればいいですか？

いえいえー
そうですね、会社のアカウントでお願いします〜
@chiharakenta このあたりサポートできる？

2020-12-02 10:10 UTC, Kazu950 commented
@75asa 
了解しました！

現在、コードをsrc/functions/ に移すことはできたのですが、
firebase login コマンドを打ってログインしようとするとESETに弾かれて
しまってログインできない状態にあり、それを解消しています。

それがもう少しかかりそうなので今日のところはとりあえず
動作確認できてないんですけど新しく作ったブランチのPR
出してもいいですか？？

2020-12-02 10:11 UTC, 75asa commented
いいよーーーーーー

2020-12-02 10:30 UTC, 75asa commented
@Kazu950 今後やり取りは新しいほうの PR でしましょー

2020-12-02 10:32 UTC, Kazu950 commented
@75asa 
了解です！
コードが本当に動くものかわからないのでdraft PR で
出した方がいいですか？

2020-12-02 10:34 UTC, 75asa commented
@Kazu950 はい、基本的に WIP 系統は draft で出してください
また レビューオッケーになっても手戻りが発生した場合、再度 draft にすることも可能です

2020-12-04 04:39 UTC, 75asa commented
#30 ができたので archive

2020-12-04 04:39 UTC, closed without merging