入部申請モーダルの項目変更
tam-bourine/club-manager pull request #152
Opened 2021-02-22 06:35 UTC by g-nemo9

**_What I did / 技術的変更点概要_**

**_Review Point / レビューしてほしい内容_**

**_Test result & Test points / テスト結果とテスト項目_**

- [ ] ...
- [ ] ...

**_Additional context / 追記・備考_**

Add any other context about the problem here.

2021-02-22 10:36 UTC, g-nemo9 reviewed
@Kazu950 @shuta13 @tk-ozawa 
お手隙の時にレビュー（確認）お願いします！

2021-02-22 10:36 UTC, g-nemo9 commented on src/functions/blocks/inputClub.ts
> +  inputComponentKibelaUrl,
副部長フィールドの削除、部費の使用用途フィールドの追加、部活動チャンネルフィールドの追加、フィールドの順番の変更を行っています。

2021-02-23 16:13 UTC, tk-ozawa requested changes
@g-nemo9 コメント書きました~

2021-02-23 16:13 UTC, tk-ozawa commented on src/functions/config/clubConfig.ts
> +    export const kibelaUrl = "Kibela URL";
`Kibela URL`って項目、ぱっと見何のurlなのかわからないからそれ誘導する必要あるかも
e.g. `部活紹介記事のKibela URL`

2021-02-24 02:32 UTC, g-nemo9 reviewed
@tk-ozawa さんにコメントもらったところを修正しました。お手隙の時にご確認ください。

2021-02-24 02:32 UTC, g-nemo9 commented on src/functions/config/clubConfig.ts
> +    export const kibelaUrl = "部活動紹介記事のKibelaのURL";
Kibela URLのフィールドのラベルをわかりやすく修正しました。

2021-02-24 02:38 UTC, tk-ozawa approved these changes
![LGTM](https://image.lgtmoon.dev/72912)

2021-02-24 03:34 UTC, shuta13 approved these changes
[![LGTM](https://lgtm.page.link/7XQvx3epwxaWFFHWA)](https://media0.giphy.com/media/ITnn2IenMv7SE/200w.gif)

2021-02-24 03:34 UTC, merged