OpenAPI(Swagger)でGAS用のAPIドキュメント作成
tam-bourine/club-manager pull request #19
Opened 2020-11-20 07:59 UTC by chiharakenta

# 実装の概要
close #16 の作成
- GASでnode.jsと連携するために、APIを作成する必要があるため。

# 実装の詳細
- GASでは、URLは1つであり、"/"を使ったルーティングはできないため、パラメーターを用いてルーティングするように定義した。
- "/"がパスの先頭ではないため、エラーが発生してしまっているが、"/?actions="ではニュアンスが変わってしまうため、一旦妥協している。

# 確認方法
- 何らかの拡張機能で /docs/gas_api/swagger.jsonをプレビューする。(vscodeならswagger viewer)
or
- https://editor.swagger.io/ に下記の [json](docs/gas_api/OpenApi.json) を貼り付ける。
```json
{
    "openapi":"3.0.2",
    "info": {
        "title":"GAS API",
        "version":"1.0",
        "description": "GAS API"
    },
    "tags": [
        {
            "name": "club"
        }
    ],
    "paths": {
        "?action=regist": {
            "post": {
                "tags": ["club"],
                "summary": "創部申請",
                "description": "部活動シートの末尾に申請のあった部活を追加します。",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "club_name": {
                                        "type": "string"
                                    },
                                    "club_description": {
                                        "type": "string"
                                    },
                                    "captain": {
                                        "type": "string"
                                    },
                                    "collaborator1": {
                                        "type": "string"
                                    },
                                    "collaborator2": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "成功時のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "integer",
                                            "example": 201
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "201 Created"
                                        },
                                        "success": {
                                            "type": "boolean",
                                            "example": true
                                        }
                                    }
                                }    
                            }
                        }
                    },
                    "500": {
                        "description": "失敗時のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "integer",
                                            "example": 500
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "500 Internal Server Error"
                                        },
                                        "success": {
                                            "type": "boolean",
                                            "example": false
                                        }
                                    }
                                }    
                            }
                        }
                    }
                }
            }
        },
        "?action=approve": {
            "post": {
                "summary": "創部承認",
                "description": "該当部活動の認可をTRUEにして、新しく部活動タブを作成する",
                "tags": ["club"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "club_name": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "成功時のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "integer",
                                            "example": 201
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "201 Created"
                                        },
                                        "success": {
                                            "type": "boolean",
                                            "example": true
                                        }
                                    }
                                }    
                            }
                        }
                    },
                    "500": {
                        "description": "失敗時のレスポンス",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "status": {
                                            "type": "integer",
                                            "example": 500
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "500 Internal Server Error"
                                        },
                                        "success": {
                                            "type": "boolean",
                                            "example": false
                                        }
                                    }
                                }    
                            }
                        }
                    }
                }
            }
        },
        "?action=join": {
            "post": {
                "summary": "参加申請",
                "description": "申請のあった該当部活動シートに、申請者の名前を追加",
                "tags": ["club"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "club_name": {
                                        "type": "string"
                          [...]

2020-11-21 01:45 UTC, 75asa requested changes
@chiharakenta @Kazu950 ざっくりみました、レスポンス的なやつはオッケーです
ちょっと細かいですが型的なやつとテーブル構成とI/F的な観点でコメントいれてます

2020-11-21 01:45 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    }
@chiharakenta @Kazu950 
Slack のワークフローをどうするかにもよるんだけど
collaborator はこんな感じで複数ユーザを配列で指定したい
![image](https://user-images.githubusercontent.com/35181442/99864203-6fe95580-2be5-11eb-9bbd-c98a876c1dc1.png)
これは部活によっちゃ collaborator は2人以上で出したいって時もクリアになるので
まあ、なのでここは `string []` にしたく思います
I/F では2人以上を指定してください〜って Validation 入れれば実現できるかなって思います

2020-11-21 01:45 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    },
club_name が変わる可能性を考慮したがいいと思うので一意のIDにしたがいいと思いました

2020-11-21 01:45 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    }
ここも創部申請と同じで ID, name で管理したいです

2020-11-21 01:45 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    },
ここなんだけど、 club_name を <ID, club_name> の配列で関して、ユーザに選ばせる I/F にしたいよね
API としては string でいいんだけど

2020-11-25 05:23 UTC, Kazu950 commented on docs/gas_api/OpenApi.json
> +                                    }
@75asa 
Slackのワークフローで作成すると、複数人指定するならその分項目を追加する必要があるみたいです。
なのでユーザーに初期メンバーの人数を委ねるのはできないっぽいんですけど、どうしますか？？

2020-11-25 05:27 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    }
なるほど、うーん
ならいったんいいかなー
ワークフローをつかう方針でいきましょうか
なので項目をわけるあんで

2020-11-25 05:37 UTC, Kazu950 commented on docs/gas_api/OpenApi.json
> +                                    }
了解です！
初期メンバーは2人設定できる感じでいいですか？

2020-11-25 12:32 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    }
@Kazu950 おkです

2020-11-25 13:06 UTC, 75asa commented
@sizukutamago レビューオナです〜

2020-11-27 00:58 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                    }
@75asa 
設計上はこのままで良し(resolve)という判断で良いですかね？

2020-11-27 01:04 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    }
はい、おっけーです

2020-11-27 01:05 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                    },
@75asa 
調べてみたところ、GAS側でuuidを振る方法があるので、
https://qiita.com/mininobu/items/ba08fb9a602e1392f5bd

リクエスト側からはclub_nameだけ受け取って、GASのシート記入の際にuuidを振るようにしたら良いかな〜と思ったのですが、いかがでしょうか。

2020-11-27 01:09 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                    }
こっちはid必要ですね。

ということは、承認用のボタンに部活id持たせないといけないので、?action=registで作成成功時のレスポンスに、作成できた部活動のオブジェクトも加える必要がありそうですね。

2020-11-27 01:12 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    },
いいね！
これでいこう！

2020-11-27 01:15 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    }
そうね、いれたがええかも

2020-11-27 01:24 UTC, 75asa commented
@tamayan ↑手隙のタイミングでレビューなどあればぜひ！！

2020-11-27 01:31 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                    },
ここも、このエンドポイント自体は、idだけで良さそうですね。

変更点としては、入部申請時に現在の部活動一覧を拾ってくるためのエンドポイントが別に必要そうですね。（名前を手入力だと、間違った時どうするんだというのが完全に認識の範囲外だった。）
どう実装するかも含めて森くんと相談してみます。

2020-11-27 01:57 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                    }
@75asa 
２点とも変更しましたので、確認してお願いします！

id利用への変更
- https://github.com/tam-bourine/club-entry-manager/pull/19/commits/bd69870db8777549d4d905b90112500dc02915f4
レスポンスに部活追加
- https://github.com/tam-bourine/club-entry-manager/pull/19/commits/366e9e8eb3a8322bf19f7c7776287b2ddfa535ba

2020-11-27 02:14 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    },
そうね、一応エンドポイントして、部活一覧があるといいよね
ここの入部自体はGAS内部関数を呼べばいいけど、べっと将来的には入りそう
あと将来的な機能として部活動名変更・部員削除機能は地味に入りそうだと思ってるのでそこを踏まえて設計すると尚いいかも
↑の二つはイシュー立てます

2020-11-27 02:18 UTC, 75asa requested changes
@chiharakenta 命名に関してリクエストです

2020-11-27 02:18 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    "collaborator1": {
```suggestion
                                    "collaborator_1 || collaborator_1st": {
```

細かいし宗教かもだけど、a-z.0-9 ではなく記号挟みたい
それと 1 だけでなく順番を連想されるように 1st とかにしたい

2020-11-27 02:18 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                    "collaborator2": {
```suggestion
                                    "collaborator_2 || collaborator_2nd": {
```
ここも同じく

2020-11-27 07:17 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                    "collaborator1": {
1st, 2ndの方で合わせました〜

2020-11-27 08:46 UTC, 75asa reviewed
やったことまとめ

2020-11-27 08:46 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +    },
〜〜なため修正 （WHY）

2020-11-27 08:46 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                        },
ここどう？〜なんだけど

2020-11-27 09:06 UTC, 75asa requested changes
@chiharakenta 一点修正確認お願いします〜

2020-11-27 09:06 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                "tags": ["club"],
```suggestion
                "tags": ["clubs"],
```
複数形では？

2020-11-27 09:06 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
メンバー一覧もいるのでは？

2020-11-27 09:06 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "鳥貴族",
LOL

2020-11-30 05:38 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                "tags": ["club"],
@75asa 
その通りですね。
修正いたしました。
https://github.com/tam-bourine/club-manager/pull/19/commits/633dfd7bebd0a4ff32f46d78745ae7561206c762

2020-11-30 09:01 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
@75asa 
確かにその通りです！
そうなると、今更ですけど、メンバーはSlackID管理すべきでしょうかね？
ユーザーグループを使うとなると、必要になりそうなので。

2020-11-30 09:02 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "鳥貴族",
www

2020-11-30 09:35 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
@chiharakenta そうだね、いるね<ID, 森貴族> 的に管理したらどうかな？

2020-12-04 03:29 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
@75asa 
<ID, 森貴族>的にって言うのは
こんな感じの認識であってるでしょうか？
```json
{
    "id": "f00tsa1",
    "name": "フットサル部",
    "members": [
        {
            "id": "m0r1kz9",
            "name": "森一貴",
            "position": "部長"
        },
        {
            "id": "ch18ken",
            "name": "千原健太",
            "position": "副部長"
        }
    ],
    "official": true
}
```

DBの構造としてはこんな形にしたのですが。
![image](https://user-images.githubusercontent.com/39648121/101118182-ec3f5800-362b-11eb-99da-8c09c7336485.png)
![image](https://user-images.githubusercontent.com/39648121/101118251-0a0cbd00-362c-11eb-9ad4-c3daab70a81d.png)

2020-12-04 03:31 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
@75asa 
一応自分の認識としては、「入部申請時に選択肢を表示するためのエンドポイント」だったので、

考えたみた結果、
ここでは公認の部活動の **idと名前だけ配列で返しす** として、部員も含めたエンドポイントは、ベータ版の部活動一覧表示の仕様を決めてからでも良いかと思いました。
なので、issueだけ立てて、ここでは↑ができた段階でresolveしようと思うのですがいかがでしょうか

2020-12-04 04:51 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
@chiharakenta いいと思う！スコープ切るのはいいこと 🚀 
念のため確認だけど 部員id は Slack ID で認識あってる？

2020-12-04 05:11 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
@75asa 
Slack idで合ってます！
確かに、部活動で使うオリジナルのuuidと区別つけないと分かりにくいですね。

こんな形で良いでしょうか？
![image](https://user-images.githubusercontent.com/39648121/101123975-5c080f80-3639-11eb-8b3e-b6ad0cc58c89.png)
![image](https://user-images.githubusercontent.com/39648121/101123944-4b579980-3639-11eb-9af4-05bf4866800b.png)

2020-12-04 05:37 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
@chiharakenta SlackID だけでいい気もします、それと退部日もしくは在籍フラグもあった方がいいきがしてます
（退社した人のことを考える）

2020-12-04 05:49 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "collaborator_2nd": "森貴族",
承知しました〜

2020-12-04 05:57 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "name": "ほげ部"
@75asa 
変更完了& #33 に別issues立てましたので、他に問題なさそうならマージお願いいたします。

2020-12-04 05:57 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "name": "ほげ部"
DB最終形態
![image](https://user-images.githubusercontent.com/39648121/101127391-d12b1300-3640-11eb-93cc-f86fef32cfae.png)
![image](https://user-images.githubusercontent.com/39648121/101127403-d5efc700-3640-11eb-96d6-62dfb1e54cb3.png)

2020-12-04 06:05 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                                    "name": "ほげ部"
## 部活マスタ
![image](https://user-images.githubusercontent.com/35181442/101127778-99709b00-3641-11eb-887d-870a8a1c7488.png)
部長、発起人1, 2 と離れて SlackID列があるのが気にあるけど基本的にはオッケーです！

## 部活詳細
いいです！LGTM！

2020-12-04 06:06 UTC, 75asa reviewed
@chiharakenta 一個だけ質問です 🙄

2020-12-04 06:06 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                        "type": "string"
1st, 2nd は微妙でした？

2020-12-04 06:24 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                        "type": "string"
@75asa 
すいませんご報告忘れてました。

idとnameをつけるとアンダーバーが2回続くのが個人的にう〜んって感じですね。
割とアンダーバー2個続くのも一般的なんでしょうか？
```
{
    "collaborator_1st_id": {
        "type": "string"
    },
    "collaborator_1st_name": {
        "type": "string"
    },
    "collaborator_2nd_id": {
        "type": "string"
    },
    "collaborator_2nd_name": {
        "type": "string"
    }
}
```

2020-12-04 06:27 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                        "type": "string"
いくつかつくのはわりと一般的かなとはおもうけど
1st, 2nd とかは suffix にするほうがメジャーなきがします

2020-12-04 07:02 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                        "type": "string"
そうなんですね。
それでは、suffixの方でやってみます！

2020-12-04 07:04 UTC, 75asa commented on docs/gas_api/OpenApi.json
> +                                        "type": "string"
遠慮なくこーゆーのコメントでいってね〜

2020-12-04 07:15 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                        "type": "string"
ありがとうございます。
今回は普通にコメント忘れてましたので気をつけます💦

変更いたしました。

2020-12-04 07:17 UTC, chiharakenta commented on docs/gas_api/OpenApi.json
> +                                                    "name": "ほげ部"
@75asa 
IDが離れていることに関しては、コーポレートの人が見た時に、
IDと混じっていると分かりにくいな〜と感じたのでこの形にしてます。

2020-12-04 07:22 UTC, 75asa approved these changes
[LGTM](https://user-images.githubusercontent.com/35181442/101133843-d8f0b480-364c-11eb-8e34-adcd2e487d38.gif)

2020-12-04 07:23 UTC, merged