GAS 創部承認
tam-bourine/club-manager pull request #94
Opened 2021-01-25 08:42 UTC by chiharakenta

**_What I did / 技術的変更点概要_**

**_Review Point / レビューしてほしい内容_**

**_Test result & Test points / テスト結果とテスト項目_**

- [ ] ...
- [ ] ...

**_Additional context / 追記・備考_**

Add any other context about the problem here.

2021-01-25 09:01 UTC, 75asa reviewed
まだ draft ですが気になったことです 🙄

2021-01-25 09:01 UTC, 75asa commented on src/gas/routes.ts
> +  return ContentService.createTextOutput(JSON.stringify(res)).setMimeType(ContentService.MimeType.JSON);
なんか長いですね

```javascript
const cntntSvc, cs = ContentService
```

とかでメンバ変数にしても良いかもですね

2021-01-25 09:08 UTC, chiharakenta commented on src/gas/routes.ts
> +function doGet(e) {
わかりました！

2021-01-25 09:40 UTC, chocopc123 commented
承認時approveで受け取るparamsって↓ですか?
```
{
    "clubId": "string",
    "clubName": "string",
    "clubDescription": "string",
    "captainId": "string",
    "captainName": "string",
    "collaboratorId1st": "string",
    "collaboratorName1st": "string",
    "collaboratorId2nd": "string",
    "collaboratorName2nd": "string",
  }
```

2021-01-25 14:10 UTC, 75asa commented
@chiharakenta @chocopc123 API response, parameters に関しては、ワークフローではなくスラッシュコマンド使うように仕様変えたので修整がいりますね…
collaborator_1st, 2nd: string -> collaborators: slackId [] とかに I/F なりそうな予感

ユーザID, name はオブジェクト配列とかにするともっと良くなりそうですね

2021-01-26 04:58 UTC, 75asa commented
ref @chocopc123 @chiharakenta

2021-01-26 14:25 UTC, 75asa commented
@chocopc123 https://github.com/tam-bourine/club-manager/pull/94/checks?check_run_id=1768374319
せっかく Actions いれてるので詳細とかみるようにできたら良いですね〜
ちな、GAS 固有のクラスがないとかおこられてるのもあるので lint plugin が適用されてないかも？
そんな気がする

2021-01-27 01:03 UTC, 75asa reviewed
@chiharakenta @chiharakenta チェケラ //

2021-01-27 01:03 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +      const sheet_id: string = PropertiesService.getScriptProperties().getProperty("SPREAD_SHEET_ID");
ここ #97 で解消できました
typescript plugin gas は入れてたけど eslint plugin 入れてなかったのが原因ですね

2021-01-27 01:03 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +      const sheet_id: string = PropertiesService.getScriptProperties().getProperty("SPREAD_SHEET_ID");
sheet_id はキャメルケース許容してないのでそこは直してください

2021-01-27 01:03 UTC, 75asa commented on src/gas/routes.ts
> +/* global ContentService MembersController ClubsController */
ContentService は GAS 固有のものなのでプラグイン入れることで解消できます #97

2021-01-27 09:23 UTC, chiharakenta commented
> @chocopc123 https://github.com/tam-bourine/club-manager/pull/94/checks?check_run_id=1768374319
> せっかく Actions いれてるので詳細とかみるようにできたら良いですね〜
> ちな、GAS 固有のクラスがないとかおこられてるのもあるので lint plugin が適用されてないかも？
> そんな気がする

@chocopc123 
pushの際にESLintを利用して、コーディング規約チェックが走るようになってます。
`npm run lint`
でコーディング規約をチェックできるので、pushの前に確認して、分かる部分は修正して、わからないところはプルリクにコメント入れて聞いてみてください。
`npm run lint:fix`
を実行すると、自動で修正してくれる部分は修正してくれます。

2021-01-27 09:26 UTC, chiharakenta commented on src/gas/routes.ts
> +      };
@75asa 
Logger.logでログ出力するっていうことで合ってますか？

2021-01-27 09:28 UTC, 75asa commented on src/gas/routes.ts
> +      };
Logger でも良いですが console.log とかでも GAS リニューアルされたのでみやすくなってるのでは？

2021-01-27 09:29 UTC, 75asa commented
@chiharakenta @chocopc123 #97 の PR 参考にしてみてください（Lint パスするようにしてます）

2021-01-27 10:16 UTC, chocopc123 commented
@75asa ありがとうございます！確認させて頂きます！！

2021-01-28 07:59 UTC, chocopc123 commented
@75asa 
レビューありがとうございます！
このエラーはどういうことなのでしょうか？？
![image](https://user-images.githubusercontent.com/41476952/106107033-bb8e2180-6189-11eb-81e1-dd50a1267610.png)

2021-01-28 08:03 UTC, 75asa commented
> @75asa
> レビューありがとうございます！
> このエラーはどういうことなのでしょうか？？
> ![image](https://user-images.githubusercontent.com/41476952/106107033-bb8e2180-6189-11eb-81e1-dd50a1267610.png)

これは TS の型情報エラーですね
params に パラメータ情報を 定義してあげないとだめです
以下の記事とか参考になるかと
https://qiita.com/nogson/items/86b47ee6947f505f6a7b
interface vs type は適宜使い分けてください〜
https://qiita.com/tkrkt/items/d01b96363e58a7df830e

2021-01-28 13:17 UTC, 75asa reviewed
@chocopc123 チェケラ¯\_ʘ‿ʘ_/¯

2021-01-28 13:17 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +// eslint-disable-next-line no-unused-vars
```suggestion

// eslint-disable-next-line no-unused-vars
```

一行あけたがみやすいです

2021-01-28 13:17 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +      const sheetId: string = PropertiesService.getScriptProperties().getProperty("SPREAD_SHEET_ID");
スプレッドシートは今回複数使わないので config.ts とかつくってそこで定数管理したが使いまわしできそうですね

2021-01-28 13:17 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +        params.collaboratorId2nd,
ながい…
ここカプセル化したらスッキリしていい感じになりそうじゃない？
e.g.`addRowFromParams({ sheet: Spreadsheet, param: Parameter Interface });`

2021-01-28 13:17 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +        params.collaboratorId2nd,
それと collaborators に仕様変えてます
swagger みてみて〜

2021-01-28 13:17 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +      };
ここ response のキー名同じのかくの億劫じゃない？🙄

2021-01-28 13:17 UTC, 75asa commented on src/gas/routes.ts
> +/* global MembersController ClubsController ParameterInterface */
```suggestion
/* global MembersController ClubsController ParameterInterface */

```
ここも一行あけたい

2021-01-28 13:17 UTC, 75asa commented on src/gas/types/ParameterInterface.ts
> +  collaboratorId2nd: string;
仕様かわってるので swagger チェックおなです😎

2021-01-28 23:05 UTC, 75asa commented on src/gas/routes.ts
> +/* global MembersController ClubsController ParameterInterface */
これ Lint rule に追加しておきましょうか
@chiharakenta @shuta13

2021-01-29 00:19 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +// eslint-disable-next-line no-unused-vars
Lintのルールに入れてみても良いかも

2021-01-29 00:20 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +      const sheetId: string = PropertiesService.getScriptProperties().getProperty("SPREAD_SHEET_ID");
SpreadsheetApp.getActiveSpreadsheetもあり

2021-01-29 00:22 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +        params.collaboratorId2nd,
appendRow()関数で
配列の順番が重要なため、tsに設定した方が良い。

2021-01-29 00:23 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +        params.collaboratorId2nd,
関数化して、引数にはオブジェクト
関数内部で配列化

2021-01-29 01:17 UTC, chiharakenta commented
@chocopc123 
次回から、
修正が終わった & 確認不要なものは resolve押しちゃって大丈夫ですよ〜。
確認が必要なものなら、その旨を返信コメント入れておくとベストです！

<img width="875" alt="スクリーンショット 2021-01-29 10 14 28" src="https://user-images.githubusercontent.com/39648121/106218582-e2486880-621a-11eb-8f9d-ce84c26aea36.png">

2021-01-29 01:47 UTC, chiharakenta commented on src/gas/routes.ts
> +      };
https://github.com/tam-bourine/club-manager/pull/94/commits/4aecd310f5a1be17308702d7277270f536308ae8
一旦シンプルにconsole.errorでオブジェクトそのままLoggingしましたが、もっと良い方法あるでしょうか？

最低限のエラーロギングはできているので、あれば別のissues立てておこうと思います。

2021-01-29 01:51 UTC, 75asa commented on src/gas/routes.ts
> +      };
いんじゃない？
敷いて言えば
`console.errer({ response })` てするとオブジェクトで見れるのでロギング楽だよ〜

2021-01-29 01:53 UTC, chiharakenta commented on src/gas/routes.ts
> +      };
承知しました！

2021-01-29 02:12 UTC, chiharakenta commented on src/gas/routes.ts
> +  return ContentService.createTextOutput(JSON.stringify(res)).setMimeType(ContentService.MimeType.JSON);
Contenserviceは現状他に使う当てがないので、
Util.makeOutputとかで関数化する案を考えたのですが、いかがでしょうか。

2021-01-29 02:32 UTC, 75asa commented on src/gas/routes.ts
> +  return ContentService.createTextOutput(JSON.stringify(res)).setMimeType(ContentService.MimeType.JSON);
LGTM！

2021-01-29 02:58 UTC, chiharakenta commented on src/gas/routes.ts
> +      break;
https://github.com/tam-bourine/club-manager/pull/94/commits/da5456cb27ea7f586442a14bdb60fc1634472787 https://github.com/tam-bourine/club-manager/pull/94/commits/d6343512aa9bf08c99171efb90effa717258b55c
作成いたしました！

2021-01-29 03:05 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +// eslint-disable-next-line no-unused-vars
https://github.com/tam-bourine/club-manager/pull/94/commits/d4e3fd3027a870452ae407141fa9c9d479792a51
clasp pushの際にimpot exportは自動でコメントアウトされてpushされることが判明したため。
コメントアウトのルールは消去できました。
![image](https://user-images.githubusercontent.com/39648121/106226237-17a88280-622a-11eb-98d2-5a1e57531e19.png)

2021-01-29 03:05 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +// eslint-disable-next-line no-unused-vars
https://github.com/tam-bourine/club-manager/pull/94#discussion_r566083671
ルール追加は別コメントに書いてあるので、こちら一旦resolveします。

2021-01-29 03:31 UTC, chiharakenta commented on src/gas/routes.ts
> +      break;
↓に挙げるmakeError関数どちらの実装が良いか迷い中

現在こっちで実装していて、
```javascript
makeError(response: ResponseInterface) {
    response.success = false;
    return response;
}
```
これだと、渡す際にキー名を書く必要が出てくる。

```javascript
makeError(status: number, message: string) {
  return {
    status: status,
    message: message,
    success: false,
  };
}
```
こっちだと、キー名書かなくて済むので、https://github.com/tam-bourine/club-manager/pull/94#discussion_r566083191 の問題も解決できる。

ただし、順番間違えた時にエラーを検出させる必要があるので、
関数の引数をInterfaceとかで定義する必要がある？

2021-01-29 03:34 UTC, chiharakenta commented on src/gas/routes.ts
> +      break;
こっちに変更した場合
```javascript
  makeError(status: number, message: string) {
    return {
      status: status,
      message: message,
      success: false,
    };
  }
```

そのままだと引数の順番間違えていても、エラーが出てこないので、出てくるようにさせないといけない。
![image](https://user-images.githubusercontent.com/39648121/106228177-2ee96f00-622e-11eb-8f74-41a5749056d7.png)

2021-01-29 03:59 UTC, 75asa commented on src/gas/routes.ts
> +      break;
`makeError(response: ResponseInterface) {
    response.success = false;
    return response;
}` でいいんじゃない？
引数の型を指定してるんだったら、使うときにエラー出るし！

2021-01-29 04:26 UTC, chiharakenta commented on src/gas/routes.ts
> +      break;
わかりました！ありがとうございます！！

2021-01-29 04:41 UTC, chiharakenta commented on src/gas/routes.ts
> +/* global MembersController ClubsController ParameterInterface */
https://github.com/tam-bourine/club-manager/issues/102
にissue立てたためresolve

2021-01-29 08:39 UTC, shuta13 commented
`clasp push` でデプロイしてみたんですが動いてないっぽい

2021-01-29 09:09 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +  static get() {
`doGet()` でここが呼び出されてる（スプレッドシートから `id` と `部活動名` 全部取ってきて返すだけ）

2021-02-01 02:53 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +  static get() {
![image](https://user-images.githubusercontent.com/39648121/106409467-ea571100-6483-11eb-8e8f-5a4f764b08c2.png)

参考: https://qiita.com/nazoking@github/items/5689ba7d27d4cdfda8f5
importはコメントアウトになるのですが、exportはコメントアウトされるのではなく、
exports.関数名
みたいになってGAS上で記述エラーが出てそうなので、こちらで調べてみます。

2021-02-01 03:43 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +  static get() {
GAS default export しかできない件とか関係ある？
エラーメッセージおしえてー

2021-02-01 03:57 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +  static get() {
今のところ、部活一覧取得自体とは直接関係はなさそうでした。

2021-02-01 04:13 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +  static get() {
> GAS default export しかできない件とか関係ある？
公式の example だと普通に `export` 使ってるのでこの件気になります
https://github.com/google/clasp/blob/master/docs/typescript.md#typescript-examples

なんかここらへん原因で動いてないなら ES Module 全部滅して CommonJS で書かないといけない感じですかね 🤔 

clasp がどこまで ES Module トランスパイル出来るかわからない

2021-02-01 04:15 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +  static get() {
clasp が default export しか対応してないみたいな記述がオフィシャルの docs にあったきがする
ちよっとさがしてみて

2021-02-01 04:18 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +  static get() {
Webpack でパースちゃんとするようにしたらちゃんと ES Module 動くらしいです

https://github.com/google/clasp/blob/master/docs/typescript.md#modules-exports-and-imports

なのでもしここらへん GAS 動いてない原因だったら Webpack 入れた方がいいかも

2021-02-01 04:21 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +  static get() {
default export 対応してるならもうそれに統一したほうが楽そうなので今調べてます

2021-02-01 06:31 UTC, chiharakenta commented on src/gas/controllers/ClubsController.ts
> +  static get() {
平井さんと、シート連携とレコードデータ入れてやってみたら、無事動作確認できました。

2021-02-01 08:03 UTC, 75asa reviewed
@shuta13 @chiharakenta @Kazu950 check it out 🙄

2021-02-01 08:46 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +        ]);
これわかります

2021-02-01 08:47 UTC, shuta13 commented
なんかどこかの on Rails みたいな MVC 風味だったので、

とりあえず CRUD にして controller が超ファットになる前に切り分けました

2021-02-01 08:50 UTC, shuta13 commented on src/gas/routes.ts
> +  switch (action) {
ここのレスポンス返す部分 `views` に切り離した方がいいかも

2021-02-01 08:54 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +      const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("部活動一覧");
`Constants.ts` とかに定数で書く or 環境変数に入れる ？

2021-02-01 08:59 UTC, 75asa commented on src/gas/controllers/ClubsController.ts
> +      const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("部活動一覧");
Constants.ts で環境変数を読み込むとかでいんじゃない？
こんなイメージ
https://github.com/mangano-ito/slack-emoji-usage-report/blob/master/src/config.ts

2021-02-01 09:06 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +      const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("部活動一覧");
良さそう

2021-02-01 09:07 UTC, shuta13 commented on src/gas/utils/Util.ts
> +import ResponseInterface from "../types/ResponseInterface";
DONE

2021-02-01 09:27 UTC, shuta13 commented on src/gas/shared/Constants.ts
> +import * as dotenv from "dotenv";
GAS で dotenv がうまく動かないみたいです（require してみてもだめだった）

<img width="721" alt="スクリーンショット 2021-02-01 18 26 41" src="https://user-images.githubusercontent.com/38882716/106439488-1772e600-64bb-11eb-8472-d188cfe526ef.png">

2021-02-01 09:31 UTC, shuta13 commented on src/gas/controllers/ClubsController.ts
> +      const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName("部活動一覧");
ローカルで run すること無いと思うので `PropertiesService.getScriptProperties().getProperty` で、

 GAS にセットした環境変数読み込むだけで良さそうな気がしなくもないです

2021-02-01 09:34 UTC, 75asa commented on src/gas/shared/Constants.ts
> +import * as dotenv from "dotenv";
GAS、clasp local では ScriptProperty を proxyrequire のようにしないといけないよ

2021-02-01 10:08 UTC, chocopc123 commented on src/gas/types/ParameterInterface.ts
> +  collaboratorId2nd: string;
@75asa
現状全てのコントローラー、アクションでParameterInterfaceを呼び出してますが、
インターフェイスってエンドポイントごとに作る感じですか？
```
RegistInterface
ApproveInterface
JoinInterface
```

2021-02-02 04:29 UTC, 75asa reviewed
🙄

2021-02-02 04:29 UTC, 75asa commented on src/gas/types/ParameterInterface.ts
> +  collaboratorId2nd: string;
@chocopc123 そうですね
エンドポイントでパラメータの内容が変わるようであれば個別に作成した方がいいです

2021-02-02 08:04 UTC, chocopc123 commented on src/gas/types/ParameterInterface.ts
> +  collaboratorId2nd: string;
@75asa 
ありがとうございます！！

2021-02-03 06:33 UTC, 75asa reviewed
@chocopc123 🙄

2021-02-03 06:33 UTC, 75asa commented on src/gas/types/JoinInterface.ts
> +  };
ここ 別で定義して extends しても良いですね

2021-02-03 06:33 UTC, 75asa commented on src/gas/types/ParameterInterface.ts
> +  };
members ですかね
そしてここも共通で使えるようであれば extends したいですね

2021-02-03 06:33 UTC, 75asa commented on src/gas/types/RegistInterface.ts
> +  collaborators: [
collaborators と members 同義で表現が異なるのでこの機会に統一した方が良いですかね 🤔

2021-02-04 08:58 UTC, shuta13 commented
`src/gas/controllers/Club/RegistController.ts` いらないんじゃないか説出てきました

UML 見てたら全部 `src/gas/controllers/Club/ApproveController.ts` でやれそう（ action=regist で呼び出す場面無い気がしました）

2021-02-04 09:41 UTC, shuta13 requested changes

2021-02-04 09:41 UTC, shuta13 commented on src/gas/routes.ts
> +      return res.success(get.show());
ここ理想は `/views` の中で `res.success` 呼び出す

```ts
switch (action) {
  case "get": {
    return getView() // 名前適当です
  }
}
```

2021-02-04 10:04 UTC, shuta13 commented on src/gas/routes.ts
> +      return res.success(get.show());
DONE

2021-02-04 10:13 UTC, shuta13 commented
すません、controller の設計ミスってるので明日修正します

routes.ts からは controller のメソッドを呼び出すべきだった

2021-02-04 10:29 UTC, shuta13 commented on src/gas/routes.ts
> +      return res.success(get.show());
↑ 間違ってて、Controller の関数呼び出すだけにしたい

2021-02-04 13:41 UTC, 75asa reviewed
きになり :eye:

2021-02-04 13:41 UTC, 75asa commented on src/gas/controllers/Clubs/GetController.ts
> +  private get = new GetModel();
```suggestion
  private model = new GetModel();
```
これでも良い気がしてる
verb.verb って個人的には違和感

2021-02-04 13:41 UTC, 75asa commented on src/gas/models/Club/RegistModel.ts
> +        const today = new Date();
ここの Date、シートに入れる際に GAS 側の TZ とかも影響しない？
時間操作今回多分しないと思うけど
みやもとで痛い目結構あったので懸念
あれだったら ISO8601 とかにするのが安全かな🤔

2021-02-04 13:41 UTC, 75asa commented on src/gas/routes.ts
> +    case "get": {
ケースも定数管理したいですね

2021-02-04 13:41 UTC, 75asa commented on src/gas/routes.ts
> +    case "join": {
ここも、定数のオブジェクトつくってどんなパターンがあるかわかればみやすいなー

2021-02-05 04:08 UTC, shuta13 commented on src/gas/models/Club/RegistModel.ts
> +        const today = new Date();
`toISOString` とかの方が確かに良いかも

2021-02-05 06:24 UTC, shuta13 commented on src/gas/controllers/Clubs/GetController.ts
> +  private get = new GetModel();
DONE

2021-02-05 06:55 UTC, shuta13 commented on src/gas/models/Club/ApproveModel.ts
> +    if (params.isApproved) {
`?action=approve` 叩くときに `is_approved` みたいなフラグをリクエストの body に入れて送るみたいなの想定してます

2021-02-05 07:10 UTC, shuta13 commented on src/gas/routes.ts
> +    case "join": {
こんな感じになりました : https://github.com/tam-bourine/club-manager/pull/94/commits/797d428204664321ef868ace6caf0260fef946bb

2021-02-05 07:11 UTC, shuta13 commented on src/gas/models/Club/RegistModel.ts
> +        const today = new Date();
付けました : https://github.com/tam-bourine/club-manager/pull/94/commits/92fb8c81be0daf36bd52ba28e35fa2d1c8b7bbc0

2021-02-05 07:20 UTC, shuta13 commented on .eslintrc.json
> +    "import/extensions": [".json", ".ts"],
VSCode の eslint が import でエラー吐きまくるやつの修正です

2021-02-05 07:20 UTC, shuta13 commented on webpack.config.js
> +module.exports = {};
こいつは特にビルドプロセスには関係しない、一応追加したが不要かも

2021-02-05 07:42 UTC, shuta13 commented on src/gas/routes.ts
> +    case "get": {
https://github.com/tam-bourine/club-manager/commit/797d428204664321ef868ace6caf0260fef946bb

2021-02-05 09:52 UTC, shuta13 commented
approve でバグってるんですが、[ issue ](https://github.com/tam-bourine/club-manager/issues/107)に切り出したのでマージします @75asa

2021-02-05 09:56 UTC, shuta13 commented on src/gas/models/Club/ApproveModel.ts
> -            sheet?.getRange(7, index).setValue("checked");
直らなかった...

2021-02-05 09:57 UTC, shuta13 approved these changes

2021-02-05 10:07 UTC, shuta13 commented
@75asa @chocopc123 承認 & マージお願いします！

2021-02-05 12:15 UTC, 75asa reviewed
@shuta13 @chiharakenta @tk-ozawa @Kazu950 もう一声欲しい〜🙄

2021-02-05 12:15 UTC, 75asa commented on src/gas/models/Club/ApproveModel.ts
> +            sheet?.getRange(index, 7).setValue("checked");
ここ定数

2021-02-05 12:15 UTC, 75asa commented on src/gas/models/Club/JoinModel.ts
> +    // @ts-ignore
どこで直すかイシュー番号かいといて

2021-02-05 12:15 UTC, 75asa commented on src/gas/models/Club/RegistModel.ts
> +           */
どこのイシューで直すか描いておいてここも

2021-02-05 12:15 UTC, 75asa commented on src/gas/routes.ts
> +  const params = JSON.parse(e.postData.getDataAsString());
ここもイシュー番号〜 e.g.
```suggestion
  // FIXME: これで取れる？ #193
  // TODO: リクエストの snake case はここで全て camel case に変えたい
  const params = JSON.parse(e.postData.getDataAsString());
```

2021-02-05 12:15 UTC, 75asa commented on src/gas/shared/Constants.ts
> +// }
ここあれだよね、ユニットテスト用に GAS 由来のプロパティとかをモックにするから残してるんだよね？
その旨描いておいて欲しい、それとイシュー番号

2021-02-05 12:15 UTC, 75asa commented on src/gas/shared/types/ApproveInterface.ts
> +  is_approved: boolean;
この子だけ仲間ハズレだね

2021-02-08 03:20 UTC, chiharakenta commented
https://github.com/tam-bourine/club-manager/pull/94#pullrequestreview-584279584
> もう一声欲しい〜🙄


この辺対応します

2021-02-08 04:20 UTC, chiharakenta commented on src/gas/models/Club/ApproveModel.ts
> +            sheet?.getRange(index, 7).setValue("checked");
修正後
```javascript
        const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetTabName);
        const data = sheet?.getDataRange().getValues();
        const isApproved = true;
        data?.map((value, index) => {
          /**
           * value[0] : id
           */
          if (value[0] === clubId) {
            /**
             * 列7 : 公認
             */
            sheet?.getRange(index, approvedColumnNumber).setValue(isApproved);
          }
```

2021-02-08 04:51 UTC, chiharakenta commented on src/gas/models/Club/RegistModel.ts
> +           */
追記しました〜
```javascript
// FIXME: #109
          /**
           * 変更の可能性あり
           * members: [
           *  {
           *    id: string,
           *    name: string,
           *    post: "captain" | "collaborator" | "member"
           *  },
           *  {},
           *  {}
           * ]
           */
```

2021-02-08 05:01 UTC, chiharakenta commented on src/gas/models/Club/JoinModel.ts
> +    // @ts-ignore
#111 で対応
```javascript
  addMember(params: JoinInterface) {
    // FIXME #111
    // @ts-ignore
    return this.view.provide(params);
  }
```

2021-02-08 05:04 UTC, chiharakenta commented
@shuta13 
https://github.com/tam-bourine/club-manager/pull/94#pullrequestreview-584279584
わかる範囲で対応したので、すいませんが残りをお願いしたいです！

2021-02-08 08:00 UTC, chocopc123 approved these changes

2021-02-10 06:02 UTC, shuta13 commented on src/gas/models/Club/ApproveModel.ts
> +            sheet?.getRange(index, 7).setValue("checked");
定数扱いなので UPPER_SNAKE の方がいいかも

2021-02-10 06:03 UTC, shuta13 commented on src/gas/shared/Constants.ts
> +// }
これ issue 生えてなさそうなので生やします

2021-02-10 06:03 UTC, shuta13 commented on src/gas/shared/types/ApproveInterface.ts
> +  is_approved: boolean;
camel に直しときます

2021-02-10 06:23 UTC, shuta13 commented on src/gas/routes.ts
> +  const params = JSON.parse(e.postData.getDataAsString());
これ https://github.com/tam-bourine/club-manager/pull/94/files/58d3451859edc8e8f8a770308a472ea4b40e8fe3#diff-fcc3a139124da27a17b7d02a33a4d0ce6930d8faf2d714db66b847794701428d の仲間はずれ `is_approve` を直せばいらないはず

2021-02-10 06:27 UTC, shuta13 commented on src/gas/shared/Constants.ts
> +// }
DONE : https://github.com/tam-bourine/club-manager/pull/94/commits/6873df2d4513ff5af3f7b026e9efb0dd4eacdd85

2021-02-10 06:32 UTC, shuta13 commented on src/gas/shared/types/ApproveInterface.ts
> +  is_approved: boolean;
DONE : https://github.com/tam-bourine/club-manager/pull/94/commits/b9dbe8104129a3d592813bcfbbb054f2ef7ca05f

2021-02-10 06:32 UTC, shuta13 commented on src/gas/routes.ts
> +  const params = JSON.parse(e.postData.getDataAsString());
DONE : https://github.com/tam-bourine/club-manager/pull/94/commits/b9dbe8104129a3d592813bcfbbb054f2ef7ca05f

2021-02-10 06:37 UTC, shuta13 commented on src/gas/models/Club/ApproveModel.ts
> +            sheet?.getRange(index, 7).setValue("checked");
DONE : approvedColumnNumber

2021-02-10 06:51 UTC, shuta13 commented on src/gas/routes.ts
> +  const params = JSON.parse(e.postData.getDataAsString());
型ミスってそうなので issue に切り出してコメント突っ込んどきました https://github.com/tam-bourine/club-manager/pull/94/commits/d4ceeb6b2ab893ef6f784b08aa8eb053e490049b

2021-02-10 06:53 UTC, shuta13 commented
@75asa  もう一声 部分対応したのでチェックお願いします 🙏

2021-02-10 07:38 UTC, 75asa approved these changes
[![LGTM](https://lgtm.page.link/bE4ZyeEtz1inbTky5)](https://media0.giphy.com/media/wlKlLBf2vtXNK/200w.gif)

2021-02-10 07:48 UTC, shuta13 approved these changes
![LGTM](https://image.lgtmoon.dev/116057)

2021-02-10 07:48 UTC, merged